import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import runningHorseOnce from "../assets/running-horse-once.gif";
import Header from "./header";
import FadeContainer from "../components/FadeContainer";
import SiteTitle from "@/components/SiteTitle";
import "@fortawesome/fontawesome-svg-core/styles.css";
const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Image
          alt="running horse background"
          src={runningHorseOnce}
          // placeholder="blur"
          quality={100}
          fill
          sizes="100vw"
          style={{
            objectFit: "cover",
          }}
          unoptimized={true}
        /> */}
        <SiteTitle />
        <FadeContainer>
          <Header />
          <>{children}</>
        </FadeContainer>
      </body>
    </html>
  );
}

// eslint-disable
const metadata: Metadata = {
  title: "Heidi Marsh | Frontend Engineer",
  description: "Generated by create next app",
};

export { metadata };
/* eslint-enable */
