import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./header";
import Timer from "./Timer";
import "@fortawesome/fontawesome-svg-core/styles.css";
const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

export const metadata: Metadata = {
  title: "Heidi Marsh | Frontend Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Timer>
          <Header />
          {children}
        </Timer>
      </body>
    </html>
  );
}
